# Generated by Django 3.1.7 on 2021-05-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
    ]
