# Generated by Django 3.1.7 on 2021-05-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(max_length=250)),
                ('name', models.CharField(default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=13)),
                ('email', models.EmailField(default='', max_length=254)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
